import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useRouter } from "next/router";

import Signin from "./Signin";
import Signup from "./Signup";
const Home: NextPage = () => {
  const router = useRouter();

  const { data: session, status } = useSession();

  // if (session) {
  //   router.push("/dashboard");
  // }

  const login = () => {
    signIn();
  };
  return (
    <>
      <Head>
        <title>Tasktank</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="grid h-screen w-screen place-items-center">
        <button
          onClick={login}
          className="rounded-lg border px-4 py-2 text-lg font-semibold "
        >
          Sign In
        </button>
      </div> */}
      <Signup/>
    </>
  );
};

export default Home;
