import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const { data: session, status } = useSession();

  if (session) {
    router.push("/dashboard");
  }

  const login = () => {
    signIn();
  };
  return (
    <>
      <Head>
        <title>Tasktank</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid h-screen w-screen place-items-center">
        <button
          onClick={login}
          className="rounded-lg border px-4 py-2 text-lg font-semibold "
        >
          Sign In
        </button>
      </div>
    </>
  );
};

export default Home;
